name: Deploy Scripts

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[SCRIPTS]')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create temporary deploy folder and filter files
        run: |
          mkdir deploy
          find . -maxdepth 1 -type f ! -name "*.*" -exec cp {} deploy/ \;
          echo "Files to be deployed:"
          ls -l deploy

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_IP }}
          username: root
          key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          source: "deploy/*"
          target: "/opt/wayclip/scripts"
          strip_components: 1

      - name: Cleanup, create directory, and debug on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_IP }}
          username: root
          key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          script: |
            rm -rf /opt/wayclip/scripts/*
            mkdir -p /opt/wayclip/scripts
            echo "Contents of the target directory after deployment:"
            ls -l /opt/wayclip/scripts

      - name: Delete temporary deploy folder from runner
        run: rm -rf deploy
